# Generated by Django 3.1.7 on 2021-04-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=50)),
                ('car_plate', models.CharField(max_length=8)),
                ('accounts_receivables', models.DecimalField(decimal_places=2, max_digits=7)),
                ('balance', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6)),
                ('accounts_payable', models.CharField(max_length=50)),
                ('inv_date', models.DateField()),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
