# Generated by Django 3.1.7 on 2021-04-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikar9', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_reference',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='car_plate',
            field=models.CharField(blank=True, default=None, max_length=8),
        ),
    ]
