# Generated by Django 3.1.7 on 2021-04-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikar9', '0002_auto_20210405_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='financial_year',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submitter',
            field=models.CharField(default='Master', max_length=50),
        ),
    ]
