# Generated by Django 3.1.7 on 2021-04-05 13:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikar9', '0003_auto_20210405_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='month',
            field=models.IntegerField(default=99),
        ),
    ]
